# Generated by Django 3.2 on 2021-04-22 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(db_index=True, max_length=100)),
                ('submission_type', models.CharField(max_length=10)),
                ('submission_status', models.CharField(max_length=10)),
                ('sex', models.CharField(max_length=1)),
                ('age', models.IntegerField(default=0)),
                ('fever_temp', models.IntegerField(default=0)),
                ('fever_duration', models.IntegerField(default=0)),
                ('interpretation', models.CharField(max_length=100)),
                ('file_location', models.CharField(max_length=1000)),
                ('ts_submission', models.DateTimeField(default=django.utils.timezone.now)),
                ('ts_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Submission',
                'verbose_name_plural': 'Submissions',
            },
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cough', models.BooleanField(default=False)),
                ('flu', models.BooleanField(default=False)),
                ('sore_throat', models.BooleanField(default=False)),
                ('shiver', models.BooleanField(default=False)),
                ('headache', models.BooleanField(default=False)),
                ('faint', models.BooleanField(default=False)),
                ('hard_to_breathe', models.BooleanField(default=False)),
                ('nausea', models.BooleanField(default=False)),
                ('diarrhea', models.BooleanField(default=False)),
                ('muscleache', models.BooleanField(default=False)),
                ('abdominal_pain', models.BooleanField(default=False)),
                ('others', models.CharField(max_length=100)),
                ('comorbidities', models.CharField(max_length=100)),
                ('fever_temp', models.IntegerField(default=0)),
                ('fever_duration', models.IntegerField(default=0)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.submission')),
            ],
            options={
                'verbose_name': 'Symptom',
                'verbose_name_plural': 'Symptoms',
            },
        ),
    ]
