# Generated by Django 3.2 on 2021-04-24 06:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frontend', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submission_result',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='submission',
            name='fever_temp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('patient_id', 'author')},
        ),
    ]
