# Generated by Django 3.2 on 2021-04-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_auto_20210424_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='submission_result',
            new_name='prediction',
        ),
        migrations.AddField(
            model_name='submission',
            name='file_location_result',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='prob_covid',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='submission',
            name='prob_normal',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='submission',
            name='prob_pneu',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=8),
        ),
    ]
