# Generated by Django 3.2 on 2021-05-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_auto_20210430_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='file_location_result',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='sex',
            field=models.CharField(max_length=10),
        ),
    ]
